cmake_policy(SET CMP0077 NEW)
set(CMAKE_POLICY_DEFAULT_CMP0077 NEW)

function(add_glfw)
  if(NOT TARGET glfw)
    set(GLFW_BUILD_EXAMPLES OFF)
    set(GLFW_BUILD_TESTS OFF)
    set(GLFW_BUILD_DOCS OFF)
    add_subdirectory(glfw)
  endif()
endfunction()
add_glfw()

function(add_glm)
  if(NOT TARGET glm)
    add_subdirectory(glm)
  endif()
endfunction()
add_glm()

function(add_fmt)
  if(NOT TARGET fmt-header-only)
    set(FMT_TEST OFF)
    add_subdirectory(fmt EXCLUDE_FROM_ALL)
  endif()
endfunction()
add_fmt()

function(add_cli11)
  if(NOT TARGET CLI11)
    add_subdirectory(cli11 EXCLUDE_FROM_ALL)
  endif()
endfunction()
add_cli11()

function(add_assertions)
  add_subdirectory(assertions)
endfunction()
add_assertions()
