# An example configuration file w/ some cameras.
[[cameras]]
model = "fisheye"
dimensions = { width = 640, height = 480 }
camera_matrix = { fx = 280.0, fy = 280.0, cx = 319.5, cy = 239.5 }
distortion_coefficients = { k1 = 0.0, k2 = 0.0, k3 = 0.0, k4 = 0.0 }

# [[cameras]]
# model = "brown-conrady"
# dimensions = { width = 640, height = 480 }
# camera_matrix = { fx = 185.0, fy = 185.0, cx = 319.5, cy = 239.5 }
# distortion_coefficients = { k1 = 0.0, k2 = 0.0, k3 = 0.0, p1 = 0.0, p2 = 0.0 }

# [[cameras]]
# model = "brown-conrady"
# dimensions = { width = 640, height = 480 }
# camera_matrix = { fx = 185.0, fy = 185.0, cx = 319.5, cy = 239.5 }
# distortion_coefficients = { k1 = 0.0, k2 = 0.0, k3 = 0.0, p1 = 0.0, p2 = 0.0 }
